// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/generate-api-bridge.js
// Do not edit manually — edit src/shared/api-channels.js instead
// ═══════════════════════════════════════════════════════════════

export function getAPI() {
  if (window.electronAPI) return window.electronAPI;
  return webAPI;
}

export const webAPI = {
  // ── DOMAIN EVENTS (manual; preserved across regeneration) ──
  // __MANUAL_START__
  navigate: () => {},
  onNavigate: () => {},
  onDataChanged: () => {},
  onHealthImportProgress: () => {},
  removeHealthImportProgressListener: () => {},
  exportData: async () => {
    const response = await fetch(window.location.origin + '/api/export');
    return response.json();
  },
  importData: async () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json';
    return new Promise((resolve, reject) => {
      input.onchange = async (e) => {
        const file = e.target.files[0];
        if (!file) return resolve(null);
        const text = await file.text();
        const data = JSON.parse(text);
        const response = await fetch(window.location.origin + '/api/import', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(data),
        });
        resolve(response.json());
      };
      input.click();
    });
  },
  // __MANUAL_END__

  // ── GENERATED CRUD CHANNELS (170 methods) ──
  async getProfile() {
    const res = await fetch('/api/db:getProfile', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveProfile(arg) {
    const res = await fetch('/api/db:saveProfile', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getActivityDays() {
    const res = await fetch('/api/db:getActivityDays', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveActivityDay(arg) {
    const res = await fetch('/api/db:saveActivityDay', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getActivityKcalByType(...args) {
    const res = await fetch('/api/db:getActivityKcalByType', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSportSummaryByRange(...args) {
    const res = await fetch('/api/db:getSportSummaryByRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getActivityComparison(...args) {
    const res = await fetch('/api/db:getActivityComparison', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSportLifetimeStats() {
    const res = await fetch('/api/db:getSportLifetimeStats', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async checkHealthsync() {
    const res = await fetch('/api/db:checkHealthsync', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async installHealthsync() {
    const res = await fetch('/api/db:installHealthsync', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthsyncDbInfo() {
    const res = await fetch('/api/db:getHealthsyncDbInfo', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async syncAppleHealth(arg) {
    const res = await fetch('/api/db:syncAppleHealth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async resetAndSyncHealthsync() {
    const res = await fetch('/api/db:resetAndSyncHealthsync', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getFoodItems(arg) {
    const res = await fetch('/api/db:getFoodItems', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveFoodItem(arg) {
    const res = await fetch('/api/db:saveFoodItem', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async hideFoodItem(arg) {
    const res = await fetch('/api/db:hideFoodItem', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async unhideFoodItem(arg) {
    const res = await fetch('/api/db:unhideFoodItem', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async searchFoodItems(arg) {
    const res = await fetch('/api/db:searchFoodItems', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getMealTemplates() {
    const res = await fetch('/api/db:getMealTemplates', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getDailyPlan(arg) {
    const res = await fetch('/api/db:getDailyPlan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveDailyPlanEntry(arg) {
    const res = await fetch('/api/db:saveDailyPlanEntry', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async updateDailyPlanEntry(...args) {
    const res = await fetch('/api/db:updateDailyPlanEntry', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteDailyPlanEntries(arg) {
    const res = await fetch('/api/db:deleteDailyPlanEntries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteDailyPlanEntry(arg) {
    const res = await fetch('/api/db:deleteDailyPlanEntry', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getMealComponents(arg) {
    const res = await fetch('/api/db:getMealComponents', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveMealComponent(arg) {
    const res = await fetch('/api/db:saveMealComponent', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteMealComponent(arg) {
    const res = await fetch('/api/db:deleteMealComponent', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getElaboratedDishes() {
    const res = await fetch('/api/db:getElaboratedDishes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveElaboratedDish(arg) {
    const res = await fetch('/api/db:saveElaboratedDish', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteElaboratedDish(arg) {
    const res = await fetch('/api/db:deleteElaboratedDish', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveDish(arg) {
    const res = await fetch('/api/db:saveDish', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getDishes() {
    const res = await fetch('/api/db:getDishes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getDishIngredients(arg) {
    const res = await fetch('/api/db:getDishIngredients', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteDish(arg) {
    const res = await fetch('/api/db:deleteDish', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveDishIngredient(arg) {
    const res = await fetch('/api/db:saveDishIngredient', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async linkDishToMeal(arg) {
    const res = await fetch('/api/db:linkDishToMeal', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getMealOptions(arg) {
    const res = await fetch('/api/db:getMealOptions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getDishesForMeal(arg) {
    const res = await fetch('/api/db:getDishesForMeal', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async unlinkDish(arg) {
    const res = await fetch('/api/db:unlinkDish', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async generateDailyPlanFromDeficit(arg) {
    const res = await fetch('/api/db:generateDailyPlanFromDeficit', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getDailyPlanNutrition(arg) {
    const res = await fetch('/api/db:getDailyPlanNutrition', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async backupDinnerDefault() {
    const res = await fetch('/api/db:backupDinnerDefault', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getMeasurementSets() {
    const res = await fetch('/api/db:getMeasurementSets', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getLatestMeasurementSet() {
    const res = await fetch('/api/db:getLatestMeasurementSet', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveMeasurementSet(arg) {
    const res = await fetch('/api/db:saveMeasurementSet', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteMeasurementSet(arg) {
    const res = await fetch('/api/db:deleteMeasurementSet', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWeightEntries() {
    const res = await fetch('/api/db:getWeightEntries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveWeightEntry(arg) {
    const res = await fetch('/api/db:saveWeightEntry', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteWeightEntry(arg) {
    const res = await fetch('/api/db:deleteWeightEntry', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getExerciseLibrary() {
    const res = await fetch('/api/db:getExerciseLibrary', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveExercise(arg) {
    const res = await fetch('/api/db:saveExercise', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteExercise(arg) {
    const res = await fetch('/api/db:deleteExercise', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getTrainingSessions() {
    const res = await fetch('/api/db:getTrainingSessions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveTrainingSession(arg) {
    const res = await fetch('/api/db:saveTrainingSession', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteTrainingSession(arg) {
    const res = await fetch('/api/db:deleteTrainingSession', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getTrainingSets(arg) {
    const res = await fetch('/api/db:getTrainingSets', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveTrainingSet(arg) {
    const res = await fetch('/api/db:saveTrainingSet', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteTrainingSet(arg) {
    const res = await fetch('/api/db:deleteTrainingSet', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getTrainingRoutines() {
    const res = await fetch('/api/db:getTrainingRoutines', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveTrainingRoutine(arg) {
    const res = await fetch('/api/db:saveTrainingRoutine', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteTrainingRoutine(arg) {
    const res = await fetch('/api/db:deleteTrainingRoutine', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWorkoutPlans() {
    const res = await fetch('/api/db:getWorkoutPlans', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getPlanDays(arg) {
    const res = await fetch('/api/db:getPlanDays', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRecentExercises() {
    const res = await fetch('/api/db:getRecentExercises', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getExercisesByIds(arg) {
    const res = await fetch('/api/db:getExercisesByIds', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSessionSetsWithExercise(arg) {
    const res = await fetch('/api/db:getSessionSetsWithExercise', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWorkoutPlanDays(arg) {
    const res = await fetch('/api/db:getWorkoutPlanDays', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getEnergyBalance(arg) {
    const res = await fetch('/api/db:getEnergyBalance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWeeklyBalance() {
    const res = await fetch('/api/db:getWeeklyBalance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async adjustMealGrams(arg) {
    const res = await fetch('/api/db:adjustMealGrams', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getEnergyBalanceSummary(arg) {
    const res = await fetch('/api/db:getEnergyBalanceSummary', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSetting(arg) {
    const res = await fetch('/api/db:getSetting', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async setSetting(...args) {
    const res = await fetch('/api/db:setSetting', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getLastImportTimestamp() {
    const res = await fetch('/api/db:getLastImportTimestamp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWeightStats(...args) {
    const res = await fetch('/api/db:getWeightStats', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSettings() {
    const res = await fetch('/api/db:getSettings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveSettings(arg) {
    const res = await fetch('/api/db:saveSettings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getDashboardData() {
    const res = await fetch('/api/db:getDashboardData', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSleepAnalysis(...args) {
    const res = await fetch('/api/db:getSleepAnalysis', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getCyclingDistance(...args) {
    const res = await fetch('/api/db:getCyclingDistance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getDashboardCardData(arg) {
    const res = await fetch('/api/db:getDashboardCardData', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getPersonalRecords() {
    const res = await fetch('/api/db:getPersonalRecords', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWeeklyGoal() {
    const res = await fetch('/api/db:getWeeklyGoal', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRelativeEffort() {
    const res = await fetch('/api/db:getRelativeEffort', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getTrainingLogWeek(arg) {
    const res = await fetch('/api/db:getTrainingLogWeek', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getMonthlyCalendar(arg) {
    const res = await fetch('/api/db:getMonthlyCalendar', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getStreak() {
    const res = await fetch('/api/db:getStreak', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getTrendWeight() {
    const res = await fetch('/api/db:getTrendWeight', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getInsightsData(arg) {
    const res = await fetch('/api/db:getInsightsData', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getStrengthInsights(arg) {
    const res = await fetch('/api/db:getStrengthInsights', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRecompData(arg) {
    const res = await fetch('/api/db:getRecompData', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getYearInMotion(...args) {
    const res = await fetch('/api/db:getYearInMotion', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getDayOfWeekStats(...args) {
    const res = await fetch('/api/db:getDayOfWeekStats', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSportDistribution() {
    const res = await fetch('/api/db:getSportDistribution', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRecoveryScore() {
    const res = await fetch('/api/db:getRecoveryScore', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWeightVelocity(...args) {
    const res = await fetch('/api/db:getWeightVelocity', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWHR() {
    const res = await fetch('/api/db:getWHR', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getAutoInsights() {
    const res = await fetch('/api/db:getAutoInsights', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getStrengthPersonalRecords() {
    const res = await fetch('/api/db:getStrengthPersonalRecords', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getStrengthPlateau() {
    const res = await fetch('/api/db:getStrengthPlateau', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getStrengthScore() {
    const res = await fetch('/api/db:getStrengthScore', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWeeklyTonnage() {
    const res = await fetch('/api/db:getWeeklyTonnage', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getGoals() {
    const res = await fetch('/api/db:getGoals', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async saveGoal(arg) {
    const res = await fetch('/api/db:saveGoal', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteGoal(arg) {
    const res = await fetch('/api/db:deleteGoal', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async archiveGoal(arg) {
    const res = await fetch('/api/db:archiveGoal', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getGoalProgress(arg) {
    const res = await fetch('/api/db:getGoalProgress', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthDailySummary(...args) {
    const res = await fetch('/api/health:getDailySummary', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthWorkouts(arg) {
    const res = await fetch('/api/health:getWorkouts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthSleep(arg) {
    const res = await fetch('/api/health:getSleep', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthHRV(arg) {
    const res = await fetch('/api/health:getHRV', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthBodyMass(arg) {
    const res = await fetch('/api/health:getBodyMass', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthHRVWeekly(arg) {
    const res = await fetch('/api/health:getHRVWeekly', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthHeartRateDaily(arg) {
    const res = await fetch('/api/health:getHeartRateDaily', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthStats() {
    const res = await fetch('/api/health:getStats', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthSyncToApp() {
    const res = await fetch('/api/health:syncToApp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthHeartRateRange(...args) {
    const res = await fetch('/api/health:getHeartRateRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthHRVRange(...args) {
    const res = await fetch('/api/health:getHRVRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthSleepRange(...args) {
    const res = await fetch('/api/health:getSleepRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthWorkoutRange(...args) {
    const res = await fetch('/api/health:getWorkoutRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthWorkoutRanking(...args) {
    const res = await fetch('/api/health:getWorkoutRanking', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthRestingHeartRateRange(...args) {
    const res = await fetch('/api/health:getRestingHeartRateRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthVO2MaxRange(...args) {
    const res = await fetch('/api/health:getVO2MaxRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthExerciseTimeRange(...args) {
    const res = await fetch('/api/health:getExerciseTimeRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthDistanceSummary(...args) {
    const res = await fetch('/api/health:getDistanceSummary', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthWalkingSpeedRange(...args) {
    const res = await fetch('/api/health:getWalkingSpeedRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthFlightsClimbedRange(...args) {
    const res = await fetch('/api/health:getFlightsClimbedRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthBloodPressure(...args) {
    const res = await fetch('/api/health:getBloodPressure', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthStandingHours(...args) {
    const res = await fetch('/api/health:getStandingHours', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthExerciseTime(...args) {
    const res = await fetch('/api/health:getExerciseTime', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthWalkingDistance(...args) {
    const res = await fetch('/api/health:getWalkingDistance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthSpO2Range(...args) {
    const res = await fetch('/api/health:getSpO2Range', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthDashboardMetrics(...args) {
    const res = await fetch('/api/health:getDashboardMetrics', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: args }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSportActivities(arg) {
    const res = await fetch('/api/db:getSportActivities', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getAllSportActivities() {
    const res = await fetch('/api/db:getAllSportActivities', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSportStats() {
    const res = await fetch('/api/db:getSportStats', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async importActivityCSV(arg) {
    const res = await fetch('/api/db:importActivityCSV', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async deleteSportActivity(arg) {
    const res = await fetch('/api/db:deleteSportActivity', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWorkoutStats() {
    const res = await fetch('/api/db:getWorkoutStats', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWeeklySportSummary() {
    const res = await fetch('/api/db:getWeeklySportSummary', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getDashboardSleepTrend() {
    const res = await fetch('/api/db:getDashboardSleepTrend', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getAvailableHealthTypes() {
    const res = await fetch('/api/db:getAvailableHealthTypes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getActivityTrend(arg) {
    const res = await fetch('/api/db:getActivityTrend', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthCompliance() {
    const res = await fetch('/api/db:getHealthCompliance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthChart(arg) {
    const res = await fetch('/api/db:getHealthChart', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async setLastImportTimestamp(arg) {
    const res = await fetch('/api/db:setLastImportTimestamp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getStepsForPeriod(arg) {
    const res = await fetch('/api/db:getStepsForPeriod', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRestingHeartRate(arg) {
    const res = await fetch('/api/db:getRestingHeartRate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHeartRateVariability(arg) {
    const res = await fetch('/api/db:getHeartRateVariability', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWalkingHeartRateAverage(arg) {
    const res = await fetch('/api/db:getWalkingHeartRateAverage', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getVo2Max(arg) {
    const res = await fetch('/api/db:getVo2Max', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSleepDataForRange(arg) {
    const res = await fetch('/api/db:getSleepDataForRange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getEnvironmentalAudioExposure(arg) {
    const res = await fetch('/api/db:getEnvironmentalAudioExposure', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHeadphoneAudioExposure(arg) {
    const res = await fetch('/api/db:getHeadphoneAudioExposure', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getActiveEnergyBurned(arg) {
    const res = await fetch('/api/db:getActiveEnergyBurned', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getBasalEnergyBurned(arg) {
    const res = await fetch('/api/db:getBasalEnergyBurned', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHeartRateRecoveryOneMinute(arg) {
    const res = await fetch('/api/db:getHeartRateRecoveryOneMinute', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSixMinuteWalkTestDistance(arg) {
    const res = await fetch('/api/db:getSixMinuteWalkTestDistance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getSwimmingDistance(arg) {
    const res = await fetch('/api/db:getSwimmingDistance', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRunningGroundContactTime(arg) {
    const res = await fetch('/api/db:getRunningGroundContactTime', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRunningPower(arg) {
    const res = await fetch('/api/db:getRunningPower', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRunningSpeed(arg) {
    const res = await fetch('/api/db:getRunningSpeed', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRunningStrideLength(arg) {
    const res = await fetch('/api/db:getRunningStrideLength', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getRunningVerticalOscillation(arg) {
    const res = await fetch('/api/db:getRunningVerticalOscillation', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getBodyFatPercentage(arg) {
    const res = await fetch('/api/db:getBodyFatPercentage', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getBodyMassIndex(arg) {
    const res = await fetch('/api/db:getBodyMassIndex', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHeight(arg) {
    const res = await fetch('/api/db:getHeight', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getLeanBodyMass(arg) {
    const res = await fetch('/api/db:getLeanBodyMass', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getWaistCircumference(arg) {
    const res = await fetch('/api/db:getWaistCircumference', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
  async getHealthData(arg) {
    const res = await fetch('/api/db:getHealthData', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ args: [arg] }) });
    if (!res.ok) throw new Error('API error: ' + res.status);
    return res.json();
  },
};

// ── ROUTE REGISTRATION (validates API surface against server) ──
export const apiRoutes = [
  '/api/db:adjustMealGrams',
  '/api/db:archiveGoal',
  '/api/db:backupDinnerDefault',
  '/api/db:checkHealthsync',
  '/api/db:deleteDailyPlanEntries',
  '/api/db:deleteDailyPlanEntry',
  '/api/db:deleteDish',
  '/api/db:deleteElaboratedDish',
  '/api/db:deleteExercise',
  '/api/db:deleteGoal',
  '/api/db:deleteMealComponent',
  '/api/db:deleteMeasurementSet',
  '/api/db:deleteSportActivity',
  '/api/db:deleteTrainingRoutine',
  '/api/db:deleteTrainingSession',
  '/api/db:deleteTrainingSet',
  '/api/db:deleteWeightEntry',
  '/api/db:generateDailyPlanFromDeficit',
  '/api/db:getActiveEnergyBurned',
  '/api/db:getActivityComparison',
  '/api/db:getActivityDays',
  '/api/db:getActivityKcalByType',
  '/api/db:getActivityTrend',
  '/api/db:getAllSportActivities',
  '/api/db:getAutoInsights',
  '/api/db:getAvailableHealthTypes',
  '/api/db:getBasalEnergyBurned',
  '/api/db:getBodyFatPercentage',
  '/api/db:getBodyMassIndex',
  '/api/db:getCyclingDistance',
  '/api/db:getDailyPlan',
  '/api/db:getDailyPlanNutrition',
  '/api/db:getDashboardCardData',
  '/api/db:getDashboardData',
  '/api/db:getDashboardSleepTrend',
  '/api/db:getDayOfWeekStats',
  '/api/db:getDishIngredients',
  '/api/db:getDishes',
  '/api/db:getDishesForMeal',
  '/api/db:getElaboratedDishes',
  '/api/db:getEnergyBalance',
  '/api/db:getEnergyBalanceSummary',
  '/api/db:getEnvironmentalAudioExposure',
  '/api/db:getExerciseLibrary',
  '/api/db:getExercisesByIds',
  '/api/db:getFoodItems',
  '/api/db:getGoalProgress',
  '/api/db:getGoals',
  '/api/db:getHeadphoneAudioExposure',
  '/api/db:getHealthChart',
  '/api/db:getHealthCompliance',
  '/api/db:getHealthData',
  '/api/db:getHealthsyncDbInfo',
  '/api/db:getHeartRateRecoveryOneMinute',
  '/api/db:getHeartRateVariability',
  '/api/db:getHeight',
  '/api/db:getInsightsData',
  '/api/db:getLastImportTimestamp',
  '/api/db:getLatestMeasurementSet',
  '/api/db:getLeanBodyMass',
  '/api/db:getMealComponents',
  '/api/db:getMealOptions',
  '/api/db:getMealTemplates',
  '/api/db:getMeasurementSets',
  '/api/db:getMonthlyCalendar',
  '/api/db:getPersonalRecords',
  '/api/db:getPlanDays',
  '/api/db:getProfile',
  '/api/db:getRecentExercises',
  '/api/db:getRecompData',
  '/api/db:getRecoveryScore',
  '/api/db:getRelativeEffort',
  '/api/db:getRestingHeartRate',
  '/api/db:getRunningGroundContactTime',
  '/api/db:getRunningPower',
  '/api/db:getRunningSpeed',
  '/api/db:getRunningStrideLength',
  '/api/db:getRunningVerticalOscillation',
  '/api/db:getSessionSetsWithExercise',
  '/api/db:getSetting',
  '/api/db:getSettings',
  '/api/db:getSixMinuteWalkTestDistance',
  '/api/db:getSleepAnalysis',
  '/api/db:getSleepDataForRange',
  '/api/db:getSportActivities',
  '/api/db:getSportDistribution',
  '/api/db:getSportLifetimeStats',
  '/api/db:getSportStats',
  '/api/db:getSportSummaryByRange',
  '/api/db:getStepsForPeriod',
  '/api/db:getStreak',
  '/api/db:getStrengthInsights',
  '/api/db:getStrengthPersonalRecords',
  '/api/db:getStrengthPlateau',
  '/api/db:getStrengthScore',
  '/api/db:getSwimmingDistance',
  '/api/db:getTrainingLogWeek',
  '/api/db:getTrainingRoutines',
  '/api/db:getTrainingSessions',
  '/api/db:getTrainingSets',
  '/api/db:getTrendWeight',
  '/api/db:getVo2Max',
  '/api/db:getWHR',
  '/api/db:getWaistCircumference',
  '/api/db:getWalkingHeartRateAverage',
  '/api/db:getWeeklyBalance',
  '/api/db:getWeeklyGoal',
  '/api/db:getWeeklySportSummary',
  '/api/db:getWeeklyTonnage',
  '/api/db:getWeightEntries',
  '/api/db:getWeightStats',
  '/api/db:getWeightVelocity',
  '/api/db:getWorkoutPlanDays',
  '/api/db:getWorkoutPlans',
  '/api/db:getWorkoutStats',
  '/api/db:getYearInMotion',
  '/api/db:hideFoodItem',
  '/api/db:importActivityCSV',
  '/api/db:installHealthsync',
  '/api/db:linkDishToMeal',
  '/api/db:resetAndSyncHealthsync',
  '/api/db:saveActivityDay',
  '/api/db:saveDailyPlanEntry',
  '/api/db:saveDish',
  '/api/db:saveDishIngredient',
  '/api/db:saveElaboratedDish',
  '/api/db:saveExercise',
  '/api/db:saveFoodItem',
  '/api/db:saveGoal',
  '/api/db:saveMealComponent',
  '/api/db:saveMeasurementSet',
  '/api/db:saveProfile',
  '/api/db:saveSettings',
  '/api/db:saveTrainingRoutine',
  '/api/db:saveTrainingSession',
  '/api/db:saveTrainingSet',
  '/api/db:saveWeightEntry',
  '/api/db:searchFoodItems',
  '/api/db:setLastImportTimestamp',
  '/api/db:setSetting',
  '/api/db:syncAppleHealth',
  '/api/db:unhideFoodItem',
  '/api/db:unlinkDish',
  '/api/db:updateDailyPlanEntry',
  '/api/health:getBloodPressure',
  '/api/health:getBodyMass',
  '/api/health:getDailySummary',
  '/api/health:getDashboardMetrics',
  '/api/health:getDistanceSummary',
  '/api/health:getExerciseTime',
  '/api/health:getExerciseTimeRange',
  '/api/health:getFlightsClimbedRange',
  '/api/health:getHRV',
  '/api/health:getHRVRange',
  '/api/health:getHRVWeekly',
  '/api/health:getHeartRateDaily',
  '/api/health:getHeartRateRange',
  '/api/health:getRestingHeartRateRange',
  '/api/health:getSleep',
  '/api/health:getSleepRange',
  '/api/health:getSpO2Range',
  '/api/health:getStandingHours',
  '/api/health:getStats',
  '/api/health:getVO2MaxRange',
  '/api/health:getWalkingDistance',
  '/api/health:getWalkingSpeedRange',
  '/api/health:getWorkoutRange',
  '/api/health:getWorkoutRanking',
  '/api/health:getWorkouts',
  '/api/health:syncToApp',
];
